VIA_ENABLE = no
STENO_ENABLE = yes
STENO_PROTOCOL = geminipr
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
NKRO_ENABLE = no
MIDI_ENABLE = no
VIRTSER_ENABLE = yes
EXTRAKEY_ENABLE = no

LINK_TIME_OPTIMIZATION_ENABLE = yes
